image:
  - Visual Studio 2015

environment:
    global:
        PROJECT_NAME: PX8
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable
          PY: 3
          PYTHONPATH: C:\Python34-x64
          FEATURES: python3-sys
          compiler: msvc_msys2
          ARCH: x64
          MSYS2_ARCH: x86_64
          MSYS2_DIR: msys64
          MSYSTEM: MINGW64
          CC: x86_64-w64-mingw32-gcc

matrix:
    allow_failures:
        - CHANNEL: nightly

install:
    # Print Powershell version.
    - ps: $PSVersionTable.PSVersion
    - ps: pwd

    - set PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%

    # Install rust, x86_64-pc-windows-msvc host
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-toolchain %CHANNEL%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - if NOT "%TARGET%" == "x86_64-pc-windows-msvc" rustup target add %TARGET%

    - where gcc rustc cargo
    - rustc -Vv
    - SET PATH=%PYTHONPATH%;%PATH%
    - python --version

    # Install SDL2.
    - curl --fail --silent --show-error --location --output sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
    - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
    - set LIB=%LIB%;C:\projects\PX8\sdl2\SDL2-2.0.5\lib\x64

    # Install SDL2_Mixer.
    - curl --fail --silent --show-error --location --output sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip
    - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
    - set LIB=%LIB%;C:\projects\PX8\sdl2_mixer\SDL2_mixer-2.0.1\lib\x64
    - ps: Get-ChildItem -Recurse -Depth 4

build: false

test_script:
    - cargo build --features="cpython lua" --verbose --release

cache:
    - target
    - C:\Users\appveyor\.cargo\registry