[package]
name = "unicorn"
version = "0.0.1"
authors = ["hallucino <d@t0t0.fr>"]
description = "Unicorn console"
documentation = ""
homepage = ""
repository = ""
readme = "README.md"
keywords = ["unicorn", "python", "lua", "javascript"]
license = "MIT"
build = "build.rs"

exclude = [ ".idea/*", ".travis.yml" ]

[lib]
name       = "unicorn"
path       = "src/lib.rs"
#crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
panic = 'unwind'

[features]
default = []
editor = []
libksnd = ["chiptune/libksnd"]

[patch.crates-io]
rand = { git = "https://github.com/hallucino/rand.git", branch = "wasm" }

[dependencies]
regex = "0.2.1"
byteorder = "1.0.0"
rand = "0.4"
libc = "0.2.18"
log = "0.3.6"
fern = "0.3.5"
rusttype = "0.2.1"
gif = "0.9.0"
lazy_static = "0.1.*"
serde = "1"
serde_derive = "1"
serde_json = "1"
num-traits = "0.1"
glob = "0.2.11"
clippy = {version = "*", optional = true}
gapbuffer = "0.1.1"
unicode-width = "0.1.1"
ordered-float = "0.5.0"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.4", default-features = false }

[dependencies.cpython]
version = "0.1.0"
optional = true

[dependencies.unicorn_plugin_lua]
optional = true
version="0.0.11"
path="src/plugins/lua"

[dependencies.duktape]
optional = true
version="0.0.1"
path="src/plugins/duktape"

[dependencies.chiptune]
version="0.0.1"
path="src/chiptune"

[dependencies.syntect]
optional = true
version = "1.8"

[dependencies.noise]
optional = true
version = "0.4.1"

[dependencies.image]
optional = true
version="0.18.0"
features=["png_codec"]
